<a href="https://colab.research.google.com/github/dajebbar/FreeCodeCamp-python-data-analysis/blob/main/Encoding_of_categorical_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
## Encoding of categorical variables
---

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')
%matplotlib inline

In [2]:
adult = pd.read_csv('./adult.csv')
adult.sample(3)

age     workclass  fnlwgt  ... hours-per-week  native-country   class
25689   38       Private  204527  ...             50   United-States   <=50K
11834   48   Federal-gov   50459  ...             40   United-States   <=50K
44649   73       Private  105886  ...             75   United-States   <=50K

[3 rows x 15 columns]

In [9]:
adult.rename(columns={'class':'Class'}, inplace=True)
def clean(df):
  df.columns = [x.replace('-', '_') for x in df.columns]
  return df

clean(adult)
adult.sample(3)

age   workclass  fnlwgt  ... hours_per_week  native_country   Class
15954   44     Private  137304  ...             40   United-States   <=50K
16148   79   Local-gov  132668  ...             15   United-States   <=50K
12616   47           ?  308499  ...             40   United-States   <=50K

[3 rows x 14 columns]

education_num and education features as very correlated (same), we can drop one of them

In [6]:
adult.drop('education_num', inplace=True, axis=1)

### decrease the volume of the dataset

In [10]:
adult = (
    adult.assign(
        age = adult.age.astype(np.int8),
        capital_loss = adult.capital_loss.astype(np.int16),
        hours_per_week = adult.hours_per_week.astype(np.int8),
        workclass = adult.workclass.astype('category'),
        education = adult.education.astype('category'),
        marital_status = adult.marital_status.astype('category'),
        occupation = adult.occupation.astype('category'),
        relationship = adult.relationship.astype('category'),
        race = adult.race.astype('category'),
        sex = adult.sex.astype('category'),
        native_country = adult.native_country.astype('category'),
        Class = adult.Class.astype('category'),

    )
)

## divide dataset

In [11]:
target_class = 'Class'
target = adult[target_class]
numerical_features = (
    adult.select_dtypes(include='number').columns.tolist()
)

categorical_features = (
    adult.select_dtypes(include='category').columns[:-1].tolist()
)
print(target_class)
print(numerical_features)
print(categorical_features)

Class
['age', 'fnlwgt', 'capital_gain', 'capital_loss', 'hours_per_week']
['workclass', 'education', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'native_country']


## Identify categorical variables
Categorical variables have discrete values, typically represented by string labels (but not only) taken from a finite list of possible choices. For instance, the variable native-country in our dataset is a categorical variable because it encodes the data using a finite list of possible countries (along with the ? symbol when this information is missing):

In [14]:
adult.native_country.value_counts().sort_index()

 ?                               857
 Cambodia                         28
 Canada                          182
 China                           122
 Columbia                         85
 Cuba                            138
 Dominican-Republic              103
 Ecuador                          45
 El-Salvador                     155
 England                         127
 France                           38
 Germany                         206
 Greece                           49
 Guatemala                        88
 Haiti                            75
 Holand-Netherlands                1
 Honduras                         20
 Hong                             30
 Hungary                          19
 India                           151
 Iran                             59
 Ireland                          37
 Italy                           105
 Jamaica                         106
 Japan                            92
 Laos                             23
 Mexico                          951
 

In [16]:
data_categorical = adult[categorical_features]
data_categorical.sample(10)

workclass      education  ...      sex  native_country
34243            Private        HS-grad  ...     Male   United-States
25731   Self-emp-not-inc        HS-grad  ...     Male   United-States
20995            Private   Some-college  ...   Female   United-States
9737    Self-emp-not-inc   Some-college  ...     Male   United-States
31304       Self-emp-inc        7th-8th  ...     Male               ?
25105            Private        HS-grad  ...   Female   United-States
2070             Private        HS-grad  ...   Female   United-States
38637            Private   Some-college  ...   Female   United-States
9468    Self-emp-not-inc        HS-grad  ...     Male   United-States
20050            Private        HS-grad  ...   Female   United-States

[10 rows x 8 columns]

---
# Strategies to encode categories
---

## Encoding ordinal categories
The most intuitive strategy is to encode each category with a different number. The OrdinalEncoder will transform the data in such manner. We will start by encoding a single column to understand how the encoding works.

In [17]:
data_categorical.describe().T

count unique                  top   freq
workclass       48842      9              Private  33906
education       48842     16              HS-grad  15784
marital_status  48842      7   Married-civ-spouse  22379
occupation      48842     15       Prof-specialty   6172
relationship    48842      6              Husband  19716
race            48842      5                White  41762
sex             48842      2                 Male  32650
native_country  48842     42        United-States  43832

In [18]:
from sklearn.preprocessing import OrdinalEncoder


education_column = data_categorical[['education']]

encoder = OrdinalEncoder()
encoded = encoder.fit_transform(education_column)
encoded

array([[ 1.],
       [11.],
       [ 7.],
       ...,
       [11.],
       [11.],
       [11.]])

We see that each category in `"education"` has been replaced by a numeric value. We could check the mapping between the categories and the numerical values by checking the fitted attribute `categories_`.

In [20]:
encoder.categories_

[array([' 10th', ' 11th', ' 12th', ' 1st-4th', ' 5th-6th', ' 7th-8th',
        ' 9th', ' Assoc-acdm', ' Assoc-voc', ' Bachelors', ' Doctorate',
        ' HS-grad', ' Masters', ' Preschool', ' Prof-school',
        ' Some-college'], dtype=object)]

Now, we can check the encoding applied on all categorical features.

In [21]:
data_encoded = encoder.fit_transform(data_categorical)
data_encoded[:5]

array([[ 4.,  1.,  4.,  7.,  3.,  2.,  1., 39.],
       [ 4., 11.,  2.,  5.,  0.,  4.,  1., 39.],
       [ 2.,  7.,  2., 11.,  0.,  4.,  1., 39.],
       [ 4., 15.,  2.,  7.,  0.,  2.,  1., 39.],
       [ 0., 15.,  4.,  0.,  3.,  4.,  0., 39.]])

In [22]:
encoder.categories_

[array([' ?', ' Federal-gov', ' Local-gov', ' Never-worked', ' Private',
        ' Self-emp-inc', ' Self-emp-not-inc', ' State-gov', ' Without-pay'],
       dtype=object),
 array([' 10th', ' 11th', ' 12th', ' 1st-4th', ' 5th-6th', ' 7th-8th',
        ' 9th', ' Assoc-acdm', ' Assoc-voc', ' Bachelors', ' Doctorate',
        ' HS-grad', ' Masters', ' Preschool', ' Prof-school',
        ' Some-college'], dtype=object),
 array([' Divorced', ' Married-AF-spouse', ' Married-civ-spouse',
        ' Married-spouse-absent', ' Never-married', ' Separated',
        ' Widowed'], dtype=object),
 array([' ?', ' Adm-clerical', ' Armed-Forces', ' Craft-repair',
        ' Exec-managerial', ' Farming-fishing', ' Handlers-cleaners',
        ' Machine-op-inspct', ' Other-service', ' Priv-house-serv',
        ' Prof-specialty', ' Protective-serv', ' Sales', ' Tech-support',
        ' Transport-moving'], dtype=object),
 array([' Husband', ' Not-in-family', ' Other-relative', ' Own-child',
        ' Unmarried'

We see that the categories have been encoded for each feature (column) independently. We also note that the number of features before and after the encoding is the same.

However, be careful when applying this encoding strategy: using this integer representation leads downstream predictive models to assume that the values are ordered (0 < 1 < 2 < 3... for instance).

By default, OrdinalEncoder uses a lexicographical strategy to map string category labels to integers. This strategy is arbitrary and often meaningless. For instance, suppose the dataset has a categorical variable named "size" with categories such as "S", "M", "L", "XL". We would like the integer representation to respect the meaning of the sizes by mapping them to increasing integers such as 0, 1, 2, 3. However, the lexicographical strategy used by default would map the labels "S", "M", "L", "XL" to 2, 1, 0, 3, by following the alphabetical order.

The OrdinalEncoder class accepts a categories constructor argument to pass categories in the expected ordering explicitly. 

If a categorical variable does not carry any meaningful order information then this encoding might be misleading to downstream statistical models and you might consider using one-hot encoding instead .

## Encoding nominal categories (without assuming any order)
`OneHotEncoder` is an alternative encoder that prevents the downstream models to make a false assumption about the ordering of categories. For a given feature, it will create as many new columns as there are possible categories. For a given sample, the value of the column corresponding to the category will be set to **1** while all the columns of the other categories will be set to **0**.

We will start by encoding a single feature (e.g. "education") to illustrate how the encoding works.

In [26]:
from sklearn.preprocessing import OneHotEncoder


encoder = OneHotEncoder(sparse=False)
education_encoded = encoder.fit_transform(data_categorical[['education']])
education_encoded

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

We see that encoding a single feature will give a NumPy array full of zeros and ones. We can get a better understanding using the associated feature names resulting from the transformation.



In [28]:
feature_names = encoder.get_feature_names_out(input_features=['education'])
education_encoded = pd.DataFrame(data=education_encoded, columns=feature_names)

In [29]:
education_encoded

education_ 10th  ...  education_ Some-college
0                  0.0  ...                      0.0
1                  0.0  ...                      0.0
2                  0.0  ...                      0.0
3                  0.0  ...                      1.0
4                  0.0  ...                      1.0
...                ...  ...                      ...
48837              0.0  ...                      0.0
48838              0.0  ...                      0.0
48839              0.0  ...                      0.0
48840              0.0  ...                      0.0
48841              0.0  ...                      0.0

[48842 rows x 16 columns]

Let's apply this encoding on the full dataset.

In [30]:
data_encoded = encoder.fit_transform(data_categorical)
data_encoded[:5]

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

Let's wrap this NumPy array in a dataframe with informative column names as provided by the encoder object:

In [31]:
columns_encoded = encoder.get_feature_names_out(
    input_features=data_categorical.columns
    )
pd.DataFrame(data=data_encoded, columns=columns_encoded).head()

workclass_ ?  ...  native_country_ Yugoslavia
0           0.0  ...                         0.0
1           0.0  ...                         0.0
2           0.0  ...                         0.0
3           0.0  ...                         0.0
4           1.0  ...                         0.0

[5 rows x 102 columns]

In [45]:
s = []
for x in data_categorical.columns.tolist():
  s.append(data_categorical[x].nunique())
print(sum(s))

102


## Choosing an encoding strategy
Choosing an encoding strategy will depend on the underlying models and the type of categories (i.e. ordinal vs. nominal).

Indeed, using an OrdinalEncoder will output ordinal categories. It means that there is an order in the resulting categories (e.g. 0 < 1 < 2). The impact of violating this ordering assumption is really dependent on the downstream models. Linear models will be impacted by misordered categories while tree-based models will not be.

Thus, in general OneHotEncoder is the encoding strategy used when the downstream models are linear models while OrdinalEncoder is used with tree-based models.

## Evaluate our predictive pipeline
We can now integrate this encoder inside a machine learning pipeline like we did with numerical data: let's train a linear classifier on the encoded data and check the generalization performance of this machine learning pipeline using cross-validation.

Before we create the pipeline, we have to linger on the native-country. Let's recall some statistics regarding this column.

In [46]:
data_categorical.native_country.value_counts()

 United-States                 43832
 Mexico                          951
 ?                               857
 Philippines                     295
 Germany                         206
 Puerto-Rico                     184
 Canada                          182
 El-Salvador                     155
 India                           151
 Cuba                            138
 England                         127
 China                           122
 South                           115
 Jamaica                         106
 Italy                           105
 Dominican-Republic              103
 Japan                            92
 Guatemala                        88
 Poland                           87
 Vietnam                          86
 Columbia                         85
 Haiti                            75
 Portugal                         67
 Taiwan                           65
 Iran                             59
 Greece                           49
 Nicaragua                        49
 