<a href="https://colab.research.google.com/github/dajebbar/FreeCodeCamp-python-data-analysis/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Principal Component Analysis (PCA) 

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[4, 11], [8, 4], [13, 5], [7, 14]])

## Calculate PCA through Matematically Method

- Calculate mean value (`df.mean()`)
- Calculate center value (`df - df.mean()`)
- Calculate covariance matrix (`df.T`)
- Calculate the eigen values and eigen vectors
- Calculate PCA (`eigen_vectors.T * df_center.T`)

In [3]:
df

0   1
0   4  11
1   8   4
2  13   5
3   7  14

## Step 1: calculate the mean values (X_mean & y_mean)

In [4]:
df_mean = df.mean()
df_mean

0    8.0
1    8.5
dtype: float64

## Step 2: calculate the center values

In [5]:
df_center = df - df_mean
df_center

0    1
0 -4.0  2.5
1  0.0 -4.5
2  5.0 -3.5
3 -1.0  5.5

## Step 3: calculate the covariance matrix

In [6]:
df_cov = np.cov(df_center.T)
df_cov

array([[ 14., -11.],
       [-11.,  23.]])

# Step 4: calculate the eigen values and eigen vectors

In [7]:
eig_vals, eig_vec = np.linalg.eig(df_cov)

In [8]:
eig_vals

array([ 6.61513568, 30.38486432])

In [9]:
eig_vec

array([[-0.83025082,  0.55738997],
       [-0.55738997, -0.83025082]])

## Step 5: calculate the PCA

In [10]:
df_center

0    1
0 -4.0  2.5
1  0.0 -4.5
2  5.0 -3.5
3 -1.0  5.5

In [11]:
df_center.T

0    1    2    3
0 -4.0  0.0  5.0 -1.0
1  2.5 -4.5 -3.5  5.5

In [12]:
df_center.T.shape

(2, 4)

In [13]:
eig_vec

array([[-0.83025082,  0.55738997],
       [-0.55738997, -0.83025082]])

In [14]:
eig_vec.T

array([[-0.83025082, -0.55738997],
       [ 0.55738997, -0.83025082]])

In [15]:
eig_vec.T.shape

(2, 2)

In [17]:
df_pca= np.dot(eig_vec.T, df_center.T)
df_pca

array([[ 1.92752836,  2.50825486, -2.20038921, -2.23539401],
       [-4.30518692,  3.73612869,  5.69282771, -5.12376947]])

In [20]:
df_pca = pd.DataFrame(data=df_pca.T, columns=df.columns)

In [21]:
df_pca

0         1
0  1.927528 -4.305187
1  2.508255  3.736129
2 -2.200389  5.692828
3 -2.235394 -5.123769